# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-18 15:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_blogpost_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2015, 12, 18, 15, 39, 57, 482357, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
