# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-18 15:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20151218_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Time'),
        ),
    ]
